#!/bin/python3

import math
import os
import random
import re
import sys
from functools import reduce
# Complete the aVeryBigSum function below.
def aVeryBigSum(n,ar):
    return sum(ar)
    
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    ar = list(map(int, input().rstrip().split()))

    result = aVeryBigSum(n,ar)

    fptr.write(str(result) + '\n')

    fptr.close()
