#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the repeatedString function below.
def repeatedString(s, n):
    count = 0
    for i in s:
        if i=='a':
            count+=1

    l = len(s)
    m = n//l
    t = n%l
    h =0
    for i in range(t):
        if s[i]=='a':
            h+=1

    ans = m *count+h
    return ans
if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    s = input()

    n = int(input())

    result = repeatedString(s, n)

    fptr.write(str(result) + '\n')

    fptr.close()
